apiVersion: v1
kind: Service
metadata:
  name: simpleapp
spec:
  selector:
    app: simpleapp
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 32089
  type: NodePort   # Or LoadBalancer if using cloud
  
